import type { Metadata } from "next";
import { Geist, Geist_Mono, Chewy, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const chewy = Chewy({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ['400']
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${chewy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
